version: '3'

services:
  web:
    build: ./form_app
    command: ["python", "manage.py", "migrate"]
    volumes:
      - ./form_app:/app
    ports:
      - "8001:8001"
    depends_on:
      - db


  db:
    image: postgres
    environment:
      POSTGRES_DB: your_db
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - web
