# Generated by Django 3.2.25 on 2024-08-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='identifier_fields',
            field=models.JSONField(default=dict),
        ),
    ]
