# Generated by Django 3.2.25 on 2024-08-07 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_form_identifier_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='identifier_fields',
        ),
    ]
