# Generated by Django 3.2.25 on 2024-08-12 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_form_identifier_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='preset',
            name='identifier',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
