# Generated by Django 3.2.25 on 2024-08-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_preset_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='identifier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
