# Generated by Django 3.2.25 on 2024-08-12 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_form_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='identifier',
        ),
        migrations.RemoveField(
            model_name='preset',
            name='identifier',
        ),
    ]
