# Generated by Django 3.2.25 on 2024-08-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20240812_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='identifier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
