# Generated by Django 3.2.25 on 2024-08-13 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_fieldcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldcomment',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='fieldcomment',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.form'),
        ),
    ]
