# Generated by Django 3.2.25 on 2024-08-13 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20240813_1150'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FieldComment',
        ),
    ]
