# Generated by Django 3.2.25 on 2024-08-23 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_formfield'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formfield',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='formfield',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
