# Generated by Django 3.2.25 on 2024-08-23 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20240823_2312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formfield',
            options={},
        ),
        migrations.RemoveField(
            model_name='formfield',
            name='order',
        ),
    ]
