# Generated by Django 3.2.25 on 2024-08-23 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20240823_2315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='form',
            options={'ordering': []},
        ),
    ]
