# Generated by Django 3.2.25 on 2024-08-23 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_form_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='form',
            options={},
        ),
    ]
