# Generated by Django 3.2.25 on 2024-09-06 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20240906_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormulaireResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_data', models.JSONField()),
                ('formulaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.formulaire')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
