# Generated by Django 3.2.25 on 2024-09-06 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20240906_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formsresponse',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.formulaire'),
        ),
    ]
